package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// writeGraphOutput writes a DOT graph to outputPath, choosing the format from
// the file extension: .dot, .svg, .html (.htm), or .md.
func writeGraphOutput(dotSrc, outputPath string) error {
	switch strings.ToLower(filepath.Ext(outputPath)) {
	case ".dot":
		return writeDOT(dotSrc, outputPath)
	case ".svg":
		return writeSVG(dotSrc, outputPath)
	case ".html", ".htm":
		return writeHTML(dotSrc, outputPath)
	case ".md":
		return writeMD(dotSrc, outputPath)
	default:
		return fmt.Errorf("unsupported output format %q; supported: .dot .svg .html .md", filepath.Ext(outputPath))
	}
}

func writeDOT(dotSrc, path string) error {
	return os.WriteFile(path, []byte(dotSrc), 0644)
}

func writeSVG(dotSrc, path string) error {
	cmd := exec.Command("dot", "-Tsvg")
	cmd.Stdin = strings.NewReader(dotSrc)
	out, err := cmd.Output()
	if err != nil {
		if _, notFound := err.(*exec.Error); notFound {
			return fmt.Errorf("graphviz 'dot' not found in PATH; install graphviz to generate .svg output")
		}
		if ee, ok := err.(*exec.ExitError); ok {
			return fmt.Errorf("dot failed: %s", string(ee.Stderr))
		}
		return fmt.Errorf("dot: %w", err)
	}
	return os.WriteFile(path, out, 0644)
}

func writeHTML(dotSrc, path string) error {
	// JSON-encode the DOT source so it is safe to embed in a JS string literal.
	dotJSON, err := json.Marshal(dotSrc)
	if err != nil {
		return err
	}
	html := strings.ReplaceAll(staticHTMLTemplate, "%%DOT%%", string(dotJSON))
	return os.WriteFile(path, []byte(html), 0644)
}

func writeMD(dotSrc, path string) error {
	var sb strings.Builder
	sb.WriteString("# MARTe Signal Flow Graph\n\n")
	sb.WriteString("<!-- Generated by mdt graph. To render: dot -Tsvg graph.dot -o graph.svg -->\n\n")
	sb.WriteString("```dot\n")
	sb.WriteString(dotSrc)
	if !strings.HasSuffix(dotSrc, "\n") {
		sb.WriteString("\n")
	}
	sb.WriteString("```\n")
	return os.WriteFile(path, []byte(sb.String()), 0644)
}

// staticHTMLTemplate is a self-contained HTML page that renders an embedded
// DOT graph using Viz.js loaded from a CDN (internet access required).
// %%DOT%% is replaced with the JSON-encoded DOT string.
const staticHTMLTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MARTe Signal Flow Graph</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { background: #0d1117; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
#container { width: 100vw; height: 100vh; overflow: auto; display: flex; align-items: flex-start; justify-content: center; padding: 16px; }
#graph svg { max-width: 100%; height: auto; }
#error { color: #f85149; font-family: monospace; padding: 2em; }
</style>
</head>
<body>
<div id="container"><div id="graph"></div><div id="error"></div></div>
<script src="https://cdn.jsdelivr.net/npm/viz.js@2.1.2/viz.js"></script>
<script src="https://cdn.jsdelivr.net/npm/viz.js@2.1.2/full.render.js"></script>
<script>
(function() {
  var dot = %%DOT%%;
  var viz = new Viz();
  viz.renderSVGElement(dot)
    .then(function(svg) {
      document.getElementById('graph').appendChild(svg);
    })
    .catch(function(err) {
      document.getElementById('error').textContent = 'Render error: ' + err.message;
    });
})();
</script>
</body>
</html>
`
